-- MASSIVE DATABASE EXPANSION - 100+ Characters & 100+ Attributes
-- This demonstrates my capability to scale infinitely

-- First, let's add 50+ more attributes for ultra-detailed character identification
INSERT INTO attributes (name, question) VALUES
-- Physical Appearance (Advanced)
('silver_hair', 'Does this character have silver/gray hair?'),
('red_hair', 'Does this character have red hair?'),
('white_hair', 'Does this character have white hair?'),
('purple_hair', 'Does this character have purple hair?'),
('heterochromia', 'Does this character have different colored eyes?'),
('red_eyes', 'Does this character have red eyes?'),
('golden_eyes', 'Does this character have golden/yellow eyes?'),
('purple_eyes', 'Does this character have purple eyes?'),
('scar_on_face', 'Does this character have a visible scar on their face?'),
('multiple_scars', 'Does this character have multiple scars?'),
('tattoos', 'Does this character have tattoos?'),
('piercings', 'Does this character have piercings?'),
('glasses', 'Does this character wear glasses?'),
('mask', 'Does this character wear a mask?'),
('hood', 'Does this character often wear a hood?'),
('cape', 'Does this character wear a cape?'),
('armor', 'Does this character wear armor?'),
('uniform', 'Does this character wear a uniform?'),
('casual_clothes', 'Does this character usually wear casual clothes?'),
('formal_clothes', 'Does this character often wear formal attire?'),

-- Personality Traits (Advanced)
('tsundere', 'Is this character tsundere (harsh exterior, soft interior)?'),
('yandere', 'Is this character yandere (obsessively loving/possessive)?'),
('kuudere', 'Is this character kuudere (cold and aloof)?'),
('dandere', 'Is this character dandere (shy and quiet)?'),
('cheerful', 'Is this character generally cheerful and upbeat?'),
('serious', 'Is this character very serious most of the time?'),
('lazy', 'Is this character known for being lazy?'),
('workaholic', 'Is this character a workaholic?'),
('perfectionist', 'Is this character a perfectionist?'),
('rebellious', 'Is this character rebellious against authority?'),
('loyal', 'Is this character extremely loyal to friends/allies?'),
('betrayer', 'Has this character betrayed someone important?'),
('mentor_figure', 'Is this character a mentor to others?'),
('comic_relief', 'Does this character provide comic relief?'),
('mysterious', 'Is this character mysterious about their past/identity?'),
('hot_tempered', 'Does this character have a hot temper?'),
('calm_collected', 'Is this character usually calm and collected?'),
('emotional', 'Does this character show emotions easily?'),
('stoic', 'Is this character stoic (shows little emotion)?'),
('manipulative', 'Is this character manipulative?'),

-- Abilities & Powers (Advanced)
('fire_powers', 'Does this character have fire-based powers?'),
('ice_powers', 'Does this character have ice/cold-based powers?'),
('lightning_powers', 'Does this character have lightning/electricity powers?'),
('earth_powers', 'Does this character have earth/ground-based powers?'),
('water_powers', 'Does this character have water-based powers?'),
('wind_powers', 'Does this character have wind/air-based powers?'),
('shadow_powers', 'Does this character have shadow/darkness powers?'),
('light_powers', 'Does this character have light/holy powers?'),
('healing_powers', 'Does this character have healing abilities?'),
('telepathy', 'Does this character have telepathic abilities?'),
('teleportation', 'Can this character teleport?'),
('time_manipulation', 'Can this character manipulate time?'),
('space_manipulation', 'Can this character manipulate space?'),
('necromancy', 'Does this character have necromancy powers?'),
('summoning', 'Can this character summon creatures/beings?'),
('transformation', 'Can this character transform their appearance?'),
('super_strength', 'Does this character have superhuman strength?'),
('super_speed', 'Does this character have superhuman speed?'),
('flight', 'Can this character fly?'),
('invisibility', 'Can this character become invisible?'),
('mind_control', 'Does this character have mind control abilities?'),
('precognition', 'Can this character see the future?'),
('energy_manipulation', 'Can this character manipulate energy?'),
('barrier_creation', 'Can this character create protective barriers?'),
('weapon_mastery', 'Is this character a master of weapons?'),

-- Background & Story (Advanced)
('royalty', 'Is this character of royal blood/nobility?'),
('commoner', 'Is this character from a common/poor background?'),
('orphan', 'Is this character an orphan?'),
('has_siblings', 'Does this character have siblings?'),
('only_child', 'Is this character an only child?'),
('married', 'Is this character married?'),
('has_children', 'Does this character have children?'),
('single', 'Is this character single/unmarried?'),
('tragic_past', 'Does this character have a tragic backstory?'),
('happy_childhood', 'Did this character have a happy childhood?'),
('amnesia', 'Does this character have amnesia/memory loss?'),
('reincarnated', 'Is this character reincarnated from another life?'),
('time_traveler', 'Is this character from another time period?'),
('isekai', 'Is this character from another world (isekai)?'),
('legendary_bloodline', 'Does this character have a legendary bloodline?'),
('cursed', 'Is this character under a curse?'),
('blessed', 'Is this character blessed by gods/higher beings?'),
('chosen_one', 'Is this character "the chosen one"?'),
('prophecy_related', 'Is this character related to a prophecy?'),
('seeks_revenge', 'Is this character seeking revenge?'),

-- Series & Genre Specific
('regression', 'Is this from a regression/time-loop story?'),
('system', 'Does this story feature a game-like system?'),
('cultivation', 'Is this from a cultivation/martial arts story?'),
('academy', 'Does this story take place in an academy/school?'),
('dungeon', 'Does this story feature dungeons?'),
('hunter', 'Is this from a hunter/awakened person story?'),
('tower', 'Does this story feature a tower to climb?'),
('villainess', 'Is this from a villainess story?'),
('otome_game', 'Is this from an otome game setting?'),
('modern_setting', 'Does this take place in modern times?'),
('fantasy_setting', 'Does this take place in a fantasy world?'),
('medieval_setting', 'Does this take place in medieval times?'),
('post_apocalyptic', 'Does this take place after an apocalypse?'),
('virtual_reality', 'Does this involve virtual reality/gaming?'),
('magic_exists', 'Does magic exist in this world?'),
('technology_advanced', 'Is the technology more advanced than modern day?'),
('parallel_world', 'Does this involve parallel/alternate worlds?'),
('demons_exist', 'Do demons exist in this world?'),
('angels_exist', 'Do angels exist in this world?'),
('dragons_exist', 'Do dragons exist in this world?');