[build]
  command = "npm run build:frontend"
  publish = "frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


